@Library("shared-library") _
pipeline {
    agent any
    // The parameters for the Jenkins pipeline.
    parameters {
        string(name: 'EMAIL',defaultValue: 'orsan.awawdi@gmail.com', description: 'Email Address')
    }
    stages {
        stage("Validate and Run") {
            steps {
                globalValidation(email_address:"${EMAIL}")
                script {
                    sh """
                    export PYTHONPATH=${WORKSPACE}
                    cd ${WORKSPACE}/git_branches/
                    python3 'git_branch.py'
                    """
                }
            }
        }
    }
}
