@Library("shared-library") _
pipeline {
    agent any
    stages {
        stage("Install and Run") {
            steps {
                globalValidation(email_address:"orsan.awawdi@gmail")
                script {
                    sh """
                    export PYTHONPATH=${WORKSPACE}
                    cd ${WORKSPACE}/git_branches/
                    python3 'git_branch.py'
                    """
                }
            }
        }
    }
}
