pipeline {
    agent any
    stages {
        stage("Install and Run") {
            steps {
                script {
                    sh """
                    export PYTHONPATH=${WORKSPACE}
                    pip3 install -r ${WORKSPACE}/requirements.txt
                    cd ${WORKSPACE}/git_branches/
                    python3 'git_branch.py'
                    """
                }
            }
        }
    }
}
